### ISSUE TITLE
hclwrite: support github.com/hashicorp/go-cty/cty

### ISSUE THREAD

**Issue by iyabchen** [hashicorp/hcl#546] opened 2022-07-27 04:47 UTC
hclwrite currently supports `github.com/zclconf/go-cty`. The library looks similar with `github.com/hashicorp/go-cty/cty`. However, their types/values cannot be cast into the other library easily. 

- Is there a difference between these two library, and how to use them interchangeably? 
- Could you support `github.com/hashicorp/go-cty/cty` in hclwrite? since terraform-plugin-sdk uses the hashicorp one rather than zclconf one.

**Comment by apparentlymart** [comment] 2022-08-15 16:16
Hi @iyabchen,

`hashicorp/go-cty` is a fork of the non-HashiCorp project `zclconf/go-cty` which was intended for use only with the old Terraform plugin SDK. The Terraform SDK team forked it so that they would have control over their copy of this dependency for use exclusively within the SDK, and it was not intended to use it with any other software such as HCL.

I see someone has created another issue hashicorp/terraform-plugin-sdk#1020 which covers the problem from the SDK's perspective. Since it's only that SDK which relies on this fork of the library, I think it's the SDK's responsibility to provide interoperability with the upstream cty library if there are use-cases for intermixing them. HCL has always been written against the upstream (since long before the Terraform SDK team forked it) and so `zclconf/go-cty` is the correct version to use for interoperability with the HCL ecosystem. Given that, I'm going to close this in favor of hashicorp/terraform-plugin-sdk#1020.

The other issue in the SDK repository currently seems to lack a clear use-case, since the example shown there doesn't include any use of HCL. In order to help the Terraform SDK team prioritize this request, I'd recommend sharing a real code example of what you're trying to achieve in that other issue, which will hopefully then help the Terraform SDK team to decide on the best way to meet that request. Thanks!

**Closed by apparentlymart** 2022-08-15 16:16 UTC
