### ISSUE TITLE
HCL2 not backwards compatible with HCL1 when `.` is in identifier (useful in `env` block).

### ISSUE THREAD

**Issue by eihli** [hashicorp/hcl#443] opened 2021-01-13 17:54 UTC
### HCL Template
```hcl
job "echo" {
  datacenters = ["dc1"]
  type = "batch"

  group "echo" {
    task "echo1" {
      driver = "exec"

      config {
        command = "/bin/sh"
        args    = ["-c", "echo $FOO; echo $FOO.BAR; echo ${FOO.BAR}"]
      }

      env {
        FOO = "foo"
        FOO.BAR = "foo.bar"
      }
    }
  }
}
```

### Expected behavior
I expect to be able to set an environment variable that has a `.` in the name.

### Actual behavior
I get an error when I run `nomad job run jobs/sample.hcl`:
```
Error getting job struct: Failed to parse using HCL 2. Use the HCL 1 parser with `nomad run -hcl1`, or address the following issues:
sample.hcl:16,9-12: Argument or block definition required; An argument or block definition is required here. To set an argument, use the equals sign "=" to introduce the argument value.
```

### Steps to reproduce
1. Try running the job in Nomad v1.0.1.

### References
https://github.com/hashicorp/nomad/issues/9606

**Comment by eihli** [comment] 2021-01-13 17:55
Copying this from the issue from the Nomad repo since it's more relevant to HCL.

I see HCL2 uses a Ragel state machine to scan tokens?

https://github.com/hashicorp/hcl/blob/v2.8.2/hclsyntax/generate.go
https://github.com/hashicorp/hcl/blob/v2.8.2/hclsyntax/unicode2ragel.rb

That ruby script creates this file: https://github.com/hashicorp/hcl/blob/v2.8.2/hclsyntax/unicode_derived.rl

The "Identifier" tokens (the tokens that make up the thing to the left of the = sign) are made up of ID_Start and ID_Continue tokens from the http://open-std.org/JTC1/SC22/WG21/docs/papers/2020/p1949r3.html#identifiers which is from the "Unicode Standard Annex 31. (Some standards body that defined a standard for C++ identifiers?)

So HCL2 identifiers are being treated like C++ identifiers. Should they be? Can that ruby script be modified to just add the Unicode FULL STOP character at the end of the ID_Continue list?

**Comment by dugdun** [comment] 2021-01-19 18:22
I'm running into this problem as well and have been working around it using a `template` block and adding `env = true` to make things work under HCL2 but that seems hacky.

Note that Nomad docs (https://www.nomadproject.io/docs/runtime/interpolation#dots_in_vars) even show using a dot in an attribute name and have that surrounded by quotes, but this is not valid in HCL2.

**Comment by apparentlymart** [comment] 2021-01-21 21:02
Indeed, HCL 2 requires that block attribute names be valid identifiers, which means (among other restrictions) they can't contain periods.

If Nomad were to recast that as an attribute expecting a map value then the following would work, because map keys are arbitrary strings without any character constraints:

```hcl
      env = {
        FOO = "foo"
        "FOO.BAR" = "foo.bar"
      }
```

There are some other options here that might allow Nomad to preserve the syntax shown above without requiring the change to an attribute, though they have some other implications. Probably best to discuss those tradeoffs over in the Nomad issue, because HCL 2 is working as intended here and this seems like a Nomad-language-specific detail. If folks from the Nomad team would like to hear about other options then let me know and I'll share some info in the Nomad issue.

**Comment by dugdun** [comment] 2021-01-21 21:12
Thanks for your input @apparentlymart ! I'll go over to the Nomad ticket and comment there.

**Comment by apparentlymart** [comment] 2022-04-21 17:20
It looks like hashicorp/nomad#9606 was resolved, and since that was the main motivation for this issue I'm going to close it.

As I mentioned above, it's intentional that HCL 2 has a more constrained syntax in this context because one of the deliberate changes between HCL 1 and HCL 2 was to allow (and in effect, to require) application developers to choose which of the two syntaxes they intend so that they can rely on the different guarantees provided by each.

In HCL 1 it was common for an application to return inscrutable errors or crash entirely if an author wrote a kind of item other than the one the application developer imagined, because the decoding rules and subsequent guarantees about the result are subtly different between the two cases. Unfortunately some applications ended up _relying_ on that ambiguity as we saw here; if those applications wish to adopt HCL 2 then they will need to make some design tradeoffs and commit to whichever of the two syntaxes most closely meets the language design goals.

**Closed by apparentlymart** 2022-04-21 17:20 UTC
